#!/bin/sh
changed=$(git diff --cached --name-only)
if [ -z "${changed}" ]; then
  exit 0
fi

OLDIFS=$IFS
IFS=$'\n'
for f in $changed; do
  case "$f" in
    "My project (2)/Assets/"* | "My project (2)/.vsconfig" | ".gitignore" | ".gitattributes" | ".githooks/"* | "README.md" | "LICENSE" | ".github" | "My project (2)/.githooks/pre-commit/"* )
      ;; # allowed
    *)
      echo "Commit aborted. Only files under 'My project (2)/Assets/' and essential repo files may be committed." 1>&2
      echo "Forbidden file: $f" 1>&2
      IFS=$OLDIFS
      exit 1
      ;;
  esac
done
IFS=$OLDIFS
exit 0